site_name: Tempus
theme:
  name: material
nav:
  - Epics: epics.md
  - Requisitos: requisitos.md
  - Histórias de Usuários: user-stories.md
  - Backlog: BACKLOG.md
  - Modelagem: modelagem-dados.md
  - Histórico de Alterações: historico-de-alteracoes.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
